export type PicassentPartida = {
  id: string;
  bloque: 'A' | 'B' | 'C';
  fecha: string;
  concepto: string;
  importe: string;
  documento: string;
  baseJuridica: string;
  exigibilidad: string;
  interrupcion: string;
  estadoH1: string;
  estadoH2: string;
  notas?: string;
  fuente?: string;
};

export const PICASSENT_PARTIDAS: PicassentPartida[] = [
  {
    id: 'picassent-2006-08-22-cancelacion',
    bloque: 'C',
    fecha: '2006-08-22',
    concepto: 'Cancelación Hipoteca Previa',
    importe: '16.979,00 €',
    documento: 'PENDIENTE/NO CONSTA',
    baseJuridica: 'PENDIENTE/NO CONSTA',
    exigibilidad: 'PENDIENTE/NO CONSTA',
    interrupcion: 'PENDIENTE/NO CONSTA',
    estadoH1: 'PENDIENTE/NO CONSTA',
    estadoH2: 'PENDIENTE/NO CONSTA',
    notas: 'Prescrito (según seed).',
    fuente: 'Seed DB (Desglose Demanda)',
  },
  {
    id: 'picassent-2008-09-01-prestamos',
    bloque: 'C',
    fecha: '2008-09-01',
    concepto: 'Préstamos Personales 2008',
    importe: '20.085,00 €',
    documento: 'PENDIENTE/NO CONSTA',
    baseJuridica: 'PENDIENTE/NO CONSTA',
    exigibilidad: 'PENDIENTE/NO CONSTA',
    interrupcion: 'PENDIENTE/NO CONSTA',
    estadoH1: 'PENDIENTE/NO CONSTA',
    estadoH2: 'PENDIENTE/NO CONSTA',
    notas: 'Prescrito (según seed).',
    fuente: 'Seed DB (Desglose Demanda)',
  },
  {
    id: 'picassent-2009-12-31-hipoteca',
    bloque: 'A',
    fecha: '2009-12-31',
    concepto: 'Hipoteca 2009 (Jul-Dic)',
    importe: '5.996,00 €',
    documento: 'PENDIENTE/NO CONSTA',
    baseJuridica: 'PENDIENTE/NO CONSTA',
    exigibilidad: 'PENDIENTE/NO CONSTA',
    interrupcion: 'PENDIENTE/NO CONSTA',
    estadoH1: 'PENDIENTE/NO CONSTA',
    estadoH2: 'PENDIENTE/NO CONSTA',
    notas: 'Prescrito (según seed).',
    fuente: 'Seed DB (Desglose Demanda)',
  },
  {
    id: 'picassent-2010-12-31-hipoteca',
    bloque: 'A',
    fecha: '2010-12-31',
    concepto: 'Hipoteca 2010 (Anual)',
    importe: '11.534,00 €',
    documento: 'PENDIENTE/NO CONSTA',
    baseJuridica: 'PENDIENTE/NO CONSTA',
    exigibilidad: 'PENDIENTE/NO CONSTA',
    interrupcion: 'PENDIENTE/NO CONSTA',
    estadoH1: 'PENDIENTE/NO CONSTA',
    estadoH2: 'PENDIENTE/NO CONSTA',
    notas: 'Prescrito (según seed).',
    fuente: 'Seed DB (Desglose Demanda)',
  },
  {
    id: 'picassent-2011-12-31-hipoteca',
    bloque: 'A',
    fecha: '2011-12-31',
    concepto: 'Hipoteca 2011 (Anual)',
    importe: '11.856,00 €',
    documento: 'PENDIENTE/NO CONSTA',
    baseJuridica: 'PENDIENTE/NO CONSTA',
    exigibilidad: 'PENDIENTE/NO CONSTA',
    interrupcion: 'PENDIENTE/NO CONSTA',
    estadoH1: 'PENDIENTE/NO CONSTA',
    estadoH2: 'PENDIENTE/NO CONSTA',
    notas: 'Prescrito (según seed).',
    fuente: 'Seed DB (Desglose Demanda)',
  },
  {
    id: 'picassent-2012-12-31-hipoteca',
    bloque: 'A',
    fecha: '2012-12-31',
    concepto: 'Hipoteca 2012 (Anual)',
    importe: '12.000,00 €',
    documento: 'PENDIENTE/NO CONSTA',
    baseJuridica: 'PENDIENTE/NO CONSTA',
    exigibilidad: 'PENDIENTE/NO CONSTA',
    interrupcion: 'PENDIENTE/NO CONSTA',
    estadoH1: 'PENDIENTE/NO CONSTA',
    estadoH2: 'PENDIENTE/NO CONSTA',
    notas: 'Prescrito (según seed).',
    fuente: 'Seed DB (Desglose Demanda)',
  },
  {
    id: 'picassent-2013-01-01-ibi',
    bloque: 'B',
    fecha: '2013-01-01',
    concepto: 'IBI 2013-2019 (Acumulado)',
    importe: '1.063,00 €',
    documento: 'PENDIENTE/NO CONSTA',
    baseJuridica: 'PENDIENTE/NO CONSTA',
    exigibilidad: 'PENDIENTE/NO CONSTA',
    interrupcion: 'PENDIENTE/NO CONSTA',
    estadoH1: 'PENDIENTE/NO CONSTA',
    estadoH2: 'PENDIENTE/NO CONSTA',
    notas: 'Prescrito (según seed).',
    fuente: 'Seed DB (Desglose Demanda)',
  },
  {
    id: 'picassent-2014-10-01-vehiculo',
    bloque: 'C',
    fecha: '2014-10-01',
    concepto: 'Compra Vehículo Seat León',
    importe: '13.000,00 €',
    documento: 'PENDIENTE/NO CONSTA',
    baseJuridica: 'PENDIENTE/NO CONSTA',
    exigibilidad: 'PENDIENTE/NO CONSTA',
    interrupcion: 'PENDIENTE/NO CONSTA',
    estadoH1: 'PENDIENTE/NO CONSTA',
    estadoH2: 'PENDIENTE/NO CONSTA',
    notas: 'Prescrito (según seed).',
    fuente: 'Seed DB (Desglose Demanda)',
  },
  {
    id: 'picassent-2023-11-01-retirada-juan',
    bloque: 'B',
    fecha: '2023-11-01',
    concepto: 'Retirada Juan (Objeto Demanda)',
    importe: '-32.000,00 €',
    documento: 'PENDIENTE/NO CONSTA',
    baseJuridica: 'PENDIENTE/NO CONSTA',
    exigibilidad: 'PENDIENTE/NO CONSTA',
    interrupcion: 'PENDIENTE/NO CONSTA',
    estadoH1: 'PENDIENTE/NO CONSTA',
    estadoH2: 'PENDIENTE/NO CONSTA',
    notas: 'Reclamado por actora (según seed).',
    fuente: 'Seed DB (Desglose Demanda)',
  },
  {
    id: 'picassent-2023-11-02-retirada-vicenta',
    bloque: 'B',
    fecha: '2023-11-02',
    concepto: 'Retirada Vicenta (A Compensar)',
    importe: '38.500,00 €',
    documento: 'PENDIENTE/NO CONSTA',
    baseJuridica: 'PENDIENTE/NO CONSTA',
    exigibilidad: 'PENDIENTE/NO CONSTA',
    interrupcion: 'PENDIENTE/NO CONSTA',
    estadoH1: 'PENDIENTE/NO CONSTA',
    estadoH2: 'PENDIENTE/NO CONSTA',
    notas: 'Crédito a nuestro favor (según seed).',
    fuente: 'Seed DB (Desglose Demanda)',
  },
];
